apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-spring-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app-pod
  template:
    metadata:
      labels:
        app: spring-app-pod
    spec:
      containers:
      - name: spring-app-container
        image: kub-spring-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2

---

apiVersion: v1
kind: Service
metadata:
  name: kub-spring-app-service
spec:
  selector:
    app: spring-app-pod
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer